(function(){
'use strict';
function byId(id){return document.getElementById(id)}
function element(tag,className,text){var e=document.createElement(tag);if(className)e.className=className;if(text!==undefined)e.textContent=text;return e}
var editor=byId('editor'),editorPanel=byId('editorPanel'),keyboard=byId('keyboard'),keyboardPanel=byId('keyboardPanel'),busterPanel=byId('busterPanel');
var codes=[['Backquote','Digit1','Digit2','Digit3','Digit4','Digit5','Digit6','Digit7','Digit8','Digit9','Digit0','Minus','Equal'],['KeyQ','KeyW','KeyE','KeyR','KeyT','KeyY','KeyU','KeyI','KeyO','KeyP','BracketLeft','BracketRight','Backslash'],['KeyA','KeyS','KeyD','KeyF','KeyG','KeyH','KeyJ','KeyK','KeyL','Semicolon','Quote'],['KeyZ','KeyX','KeyC','KeyV','KeyB','KeyN','KeyM','Comma','Period','Slash']];
var english={
'QWERTY':[['`','1','2','3','4','5','6','7','8','9','0','-','='],['q','w','e','r','t','y','u','i','o','p','[',']','\\'],['a','s','d','f','g','h','j','k','l',';',"'"],['z','x','c','v','b','n','m',',','.','/']],
'AZERTY':[['²','&','é','"',"'",'(','-','è','_','ç','à',')','='],['a','z','e','r','t','y','u','i','o','p','^','$','*'],['q','s','d','f','g','h','j','k','l','m','ù'],['w','x','c','v','b','n',',',';',':','!']],
'QWERTZ':[['^','1','2','3','4','5','6','7','8','9','0','ß','´'],['q','w','e','r','t','z','u','i','o','p','ü','+','#'],['a','s','d','f','g','h','j','k','l','ö','ä'],['y','x','c','v','b','n','m',',','.','-']],
'Dvorak':[['`','1','2','3','4','5','6','7','8','9','0','[',']'],["'",',','.','p','y','f','g','c','r','l','/','=','\\'],['a','o','e','u','i','d','h','t','n','s','-'],[';','q','j','k','x','b','m','w','v','z']]
};
var inscriptNormal=[['ॊ','1','2','3','4','5','6','7','8','9','0','-','ृ'],['ौ','ै','ा','ी','ू','ब','ह','ग','द','ज','ड','़','ॉ'],['ो','े','्','ि','ु','प','र','क','त','च','ट'],['ॆ','ं','म','न','व','ल','स',',','.','य']];
var inscriptShift=[['ऒ','ऍ','ॅ','्र','र्','ज्ञ','त्र','क्ष','श्र','(',')','ः','ऋ'],['औ','ऐ','आ','ई','ऊ','भ','ङ','घ','ध','झ','ढ','ञ','ऑ'],['ओ','ए','अ','इ','उ','फ','ऱ','ख','थ','छ','ठ'],['ऎ','ँ','ण','ऩ','ऴ','ळ','श','ष','।','य़']];
var remingtonNormal=[['`','1','2','3','4','5','6','7','8','9','0','-','ृ'],['ु','ू','म','त','ज','ल','न','प','व','च','ख','घ','?'],['ं','े','क','ि','ह','ी','र','ा','स','य','श'],['्र','ग','ब','अ','इ','द','उ','ए','ण','ध']];
var remingtonShift=[['~','!','@','#','$','%','^','&','*','(',')','_','्'],['फ़','ॅ','म्','त्','ज्','ल्','न्','प्','व्','च्','क्ष','झ','/'],['ँ','ै','क्','थ्','ल','भ','श्र','ज्ञ','स्','रू','ष'],['र्','ग्','ब्','ट','ठ','छ','ड','ढ','झ','घ']];
var codeButtons={},capsOn=false,virtualShift=false,savedRange=null,idleRibbonTimer=null;
var timerSeconds=0,timerHandle=null,timerArmed=false;
var sessionStart=0,totalAttempts=0,correctAttempts=0,errorAttempts=0,speedBuckets=[];
var buster=false,target='',targetSymbols=[],targetIndex=0,misses=[],savedNormal='';
function isEnglishFont(){var f=byId('font').value;return f==='Arial'||f==='Georgia'}
function isKruti(){return byId('font').value==='Kruti Dev 010'}
function isHindiFont(){return !isEnglishFont()}
function profile(){if(isEnglishFont())return 'english';if(isKruti())return 'remington';if(byId('font').value==='Chanakya')return 'chanakya';return 'inscript'}
function matrixValue(matrix,code){for(var r=0;r<codes.length;r++){var index=codes[r].indexOf(code);if(index>-1)return matrix[r][index]||''}return ''}
function latinLabel(code,upper){var map={Backquote:'`',Minus:'-',Equal:'=',BracketLeft:'[',BracketRight:']',Backslash:'\\',Semicolon:';',Quote:"'",Comma:',',Period:'.',Slash:'/'};if(code.indexOf('Key')===0){var letter=code.slice(3);return upper?letter:letter.toLowerCase()}if(code.indexOf('Digit')===0)return code.slice(5);return map[code]||''}
function mappedOutput(code,shift){var p=profile();if(p==='inscript'||p==='chanakya')return matrixValue(shift?inscriptShift:inscriptNormal,code);if(p==='remington')return matrixValue(shift?remingtonShift:remingtonNormal,code);var name=byId('layout').value;if(!english[name])name='QWERTY';var value=matrixValue(english[name],code);if(/^[a-z]$/i.test(value)){var upper=(capsOn&&!shift)||(!capsOn&&shift);return upper?value.toUpperCase():value.toLowerCase()}return value}
function addCodeButton(code,button){if(!codeButtons[code])codeButtons[code]=[];codeButtons[code].push(button)}
function makeKey(code,wideLabel){var button=element('button','key');button.type='button';button.dataset.code=code;if(wideLabel){button.classList.add('wide');button.appendChild(element('span','main',wideLabel))}else{var p=profile(),out=mappedOutput(code,virtualShift);if(p==='english'){button.appendChild(element('span','main',out))}else{button.appendChild(element('span','main',latinLabel(code,capsOn)));button.appendChild(element('span','hint',out))}}if(code==='CapsLock'&&capsOn)button.classList.add('caps-on');button.addEventListener('mousedown',function(event){event.preventDefault();activateVirtual(code)});addCodeButton(code,button);return button}
function renderKeyboard(){keyboard.textContent='';codeButtons={};var name=byId('layout').value;byId('layoutName').textContent=name;for(var r=0;r<codes.length;r++){var row=element('div','key-row');if(r===1)row.appendChild(makeKey('Tab','Tab'));if(r===2)row.appendChild(makeKey('CapsLock','Caps'));if(r===3)row.appendChild(makeKey('ShiftLeft','Shift'));for(var k=0;k<codes[r].length;k++)row.appendChild(makeKey(codes[r][k],''));if(r===0)row.appendChild(makeKey('Backspace','Backspace'));if(r===2)row.appendChild(makeKey('Enter','Enter'));if(r===3)row.appendChild(makeKey('ShiftRight','Shift'));keyboard.appendChild(row)}var bottom=element('div','key-row'),space=makeKey('Space','Space');space.classList.add('space');bottom.appendChild(space);keyboard.appendChild(bottom)}
function flashCode(code,wrong){var list=codeButtons[code]||[];for(var i=0;i<list.length;i++){(function(button){button.classList.add('pressed');if(wrong)button.classList.add('wrong-flash');setTimeout(function(){button.classList.remove('pressed');button.classList.remove('wrong-flash')},140)})(list[i])}}
function saveSelection(){var selection=window.getSelection();if(selection.rangeCount&&editor.contains(selection.anchorNode))savedRange=selection.getRangeAt(0).cloneRange()}
function restoreSelection(){if(!savedRange)return;var selection=window.getSelection();selection.removeAllRanges();selection.addRange(savedRange)}
function insertAtCursor(text){editor.focus();restoreSelection();var selection=window.getSelection();if(!selection.rangeCount){editor.appendChild(document.createTextNode(text));return}var range=selection.getRangeAt(0);range.deleteContents();var node=document.createTextNode(text);range.insertNode(node);range.setStartAfter(node);range.collapse(true);selection.removeAllRanges();selection.addRange(range);saveSelection();editor.dispatchEvent(new Event('input',{bubbles:true}));scheduleCaret()}
function actualTypingStart(){if(!sessionStart){sessionStart=Date.now();speedBuckets=[]}if(timerArmed&&timerSeconds>0&&!timerHandle)startTimer();document.body.classList.add('focus-mode');clearTimeout(idleRibbonTimer);idleRibbonTimer=setTimeout(function(){leaveFocus()},3000)}
function recordAttempt(correct){actualTypingStart();totalAttempts++;if(correct)correctAttempts++;else errorAttempts++;var second=Math.floor((Date.now()-sessionStart)/1000);while(speedBuckets.length<=second)speedBuckets.push(0);if(correct)speedBuckets[second]++}
function activateVirtual(code){editor.focus();if(code==='CapsLock'){capsOn=!capsOn;renderKeyboard();return}if(code==='ShiftLeft'||code==='ShiftRight'){virtualShift=!virtualShift;renderKeyboard();return}if(code==='Backspace'){if(buster)return;recordAttempt(false);document.execCommand('delete',false,null);editor.dispatchEvent(new Event('input',{bubbles:true}));return}var output=code==='Space'?' ':code==='Enter'?'\n':code==='Tab'?'\t':mappedOutput(code,virtualShift);flashCode(code,false);if(!output)return;if(buster)processBuster(output,latinLabel(code,true),code);else{recordAttempt(true);insertAtCursor(output)}if(virtualShift){virtualShift=false;renderKeyboard()}}
function textValue(){return (editor.innerText||'').replace(/\n$/,'')}
function sanitizeText(text){return String(text||'').replace(/\r\n?/g,'\n').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F\uFFFC]/g,'')}
function sanitizeRichHtml(html){var doc=new DOMParser().parseFromString(html,'text/html'),fragment=document.createDocumentFragment();function copyNode(node,parent){if(node.nodeType===3){parent.appendChild(document.createTextNode(sanitizeText(node.nodeValue)));return}if(node.nodeType!==1)return;var tag=node.tagName.toLowerCase(),container=parent;if(tag==='b'||tag==='strong')container=parent.appendChild(document.createElement('strong'));else if(tag==='i'||tag==='em')container=parent.appendChild(document.createElement('em'));else if(tag==='u')container=parent.appendChild(document.createElement('u'));else if(tag==='br'){parent.appendChild(document.createElement('br'));return}else if(tag==='img'||tag==='video'||tag==='audio'||tag==='iframe'||tag==='object'||tag==='embed'||tag==='svg'||tag==='canvas'||tag==='table'||tag==='script'||tag==='style')return;else if(tag==='span'){var style=(node.getAttribute('style')||'').toLowerCase(),wrap=parent;if(style.indexOf('underline')>-1)wrap=wrap.appendChild(document.createElement('u'));if(style.indexOf('italic')>-1)wrap=wrap.appendChild(document.createElement('em'));if(style.indexOf('font-weight')>-1&&(style.indexOf('bold')>-1||/[6-9]00/.test(style)))wrap=wrap.appendChild(document.createElement('strong'));container=wrap}var children=Array.prototype.slice.call(node.childNodes);for(var i=0;i<children.length;i++)copyNode(children[i],container);if((tag==='p'||tag==='div'||tag==='li')&&parent.lastChild&&parent.lastChild.tagName!=='BR')parent.appendChild(document.createElement('br'))}var roots=Array.prototype.slice.call(doc.body.childNodes);for(var i=0;i<roots.length;i++)copyNode(roots[i],fragment);return fragment}
function insertFragmentAtCursor(fragment){editor.focus();restoreSelection();var selection=window.getSelection();if(!selection.rangeCount)return;var range=selection.getRangeAt(0);range.deleteContents();var last=fragment.lastChild;range.insertNode(fragment);if(last){range.setStartAfter(last);range.collapse(true);selection.removeAllRanges();selection.addRange(range)}saveSelection();editor.dispatchEvent(new Event('input',{bubbles:true}));scheduleCaret()}
function estimateTokens(text){if(!text)return 0;var pieces=text.match(/[A-Za-z0-9]+|[\u0900-\u097F]+|\s+|[^\sA-Za-z0-9\u0900-\u097F]/gu)||[];var count=0;for(var i=0;i<pieces.length;i++){var part=pieces[i];if(/^\s+$/u.test(part))continue;if(/^[A-Za-z0-9]+$/u.test(part))count+=Math.max(1,Math.ceil(part.length/4));else if(/^[\u0900-\u097F]+$/u.test(part))count+=Math.max(1,Math.ceil(Array.from(part).length/2));else count+=Array.from(part).length}return count}
function metricsText(text){var trimmed=text.trim(),words=trimmed?trimmed.split(/\s+/u).length:0;return words+' words · '+text.length+' characters · ~'+estimateTokens(text)+' tokens'}
function updateCount(){if(buster)return;byId('count').textContent=metricsText(textValue())}
function ensureCaretVisible(){if(document.activeElement!==editor)return;var selection=window.getSelection();if(!selection.rangeCount)return;var range=selection.getRangeAt(0);if(!editor.contains(range.startContainer))return;var caret=range.getBoundingClientRect(),marker=null;if(!caret.height){var probe=range.cloneRange();probe.collapse(true);marker=document.createElement('span');marker.textContent='\u200b';probe.insertNode(marker);caret=marker.getBoundingClientRect()}var box=editor.getBoundingClientRect(),pad=28;if(caret.bottom>box.bottom-pad)editor.scrollTop+=caret.bottom-(box.bottom-pad);else if(caret.top<box.top+pad)editor.scrollTop-=box.top+pad-caret.top;if(marker&&marker.parentNode)marker.parentNode.removeChild(marker);saveSelection()}
function scheduleCaret(){setTimeout(ensureCaretVisible,0)}
function leaveFocus(){document.body.classList.remove('focus-mode')}
function formatClock(){if(timerSeconds<=0){byId('clock').textContent='∞';return}var h=Math.floor(timerSeconds/3600),m=Math.floor((timerSeconds%3600)/60),s=timerSeconds%60;byId('clock').textContent=(h?String(h).padStart(2,'0')+':':'')+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function resetSession(){sessionStart=0;totalAttempts=0;correctAttempts=0;errorAttempts=0;speedBuckets=[]}
function setTimer(seconds){clearInterval(timerHandle);timerHandle=null;timerSeconds=seconds;timerArmed=seconds>0;resetSession();formatClock()}
function startTimer(){timerArmed=false;timerHandle=setInterval(function(){timerSeconds--;formatClock();if(timerSeconds<=0){clearInterval(timerHandle);timerHandle=null;leaveFocus();finishSession()}},1000)}
function standardDeviation(values,mean){if(!values.length)return 0;var sum=0;for(var i=0;i<values.length;i++)sum+=Math.pow(values[i]-mean,2);return Math.sqrt(sum/values.length)}
function finishSession(){var elapsed=Math.max(1,(Date.now()-sessionStart)/1000),minutes=elapsed/60;var content=buster?targetSymbols.slice(0,targetIndex).join(''):textValue();var trimmed=content.trim(),words=trimmed?trimmed.split(/\s+/u).length:0;var usable=buster?correctAttempts:content.length;var netWpm=(usable/5)/minutes;var attempts=Math.max(1,totalAttempts),accuracy=(Math.max(0,totalAttempts-errorAttempts)/attempts)*100;var seconds=Math.max(1,Math.ceil(elapsed));var samples=[];for(var i=0;i<seconds;i++)samples.push((speedBuckets[i]||0)*12);var mean=samples.reduce(function(a,b){return a+b},0)/samples.length;var consistency=mean>0?Math.max(0,Math.min(100,100-(standardDeviation(samples,mean)/mean*100))):0;byId('resultWords').textContent=words;byId('resultWpm').textContent=netWpm.toFixed(1);byId('resultConsistency').textContent=consistency.toFixed(0)+'%';byId('resultAccuracy').textContent=accuracy.toFixed(1)+'%';byId('resultMethod').textContent=buster?'Net WPM uses correct characters ÷ 5 ÷ elapsed minutes. Accuracy compares every attempted key with the exercise. Consistency uses the variation of per-second speed.':'Net WPM uses final usable characters ÷ 5 ÷ elapsed minutes. Without a reference passage, accuracy is correction-based: Backspace corrections count as errors. Keys Buster provides exact target-based accuracy.';byId('resultsDialog').showModal()}
function showToast(message){var box=byId('toast');box.textContent=message;box.classList.add('show');clearTimeout(box.toastTimer);box.toastTimer=setTimeout(function(){box.classList.remove('show')},850)}
function visible(character){if(character===' ')return 'Space';if(character==='\n')return 'Enter';if(character==='\t')return 'Tab';return character}
function applyFont(){var font=byId('font').value;editor.style.fontFamily='"'+font+'","Nirmala UI","Mangal",Arial,sans-serif';renderKeyboard()}
function setBuster(on){buster=on;byId('busterToggle').classList.toggle('active',on);byId('mode').textContent=on?'Keys Buster':'Free typing';busterPanel.classList.toggle('visible',on);keyboardPanel.style.display=on?'none':'';if(on){savedNormal=editor.innerHTML;editor.contentEditable='false';editor.setAttribute('data-placeholder','Paste an exercise to begin…');if(!target)byId('textDialog').showModal();else{renderTarget();renderLane(false);editor.focus()}}else{editor.contentEditable='true';editor.innerHTML=savedNormal;editor.setAttribute('data-placeholder','Start typing here…');updateCount();editor.focus()}}
function loadTarget(){var value=byId('sourceText').value.normalize('NFC');if(!value.trim()){window.alert('Paste some text first.');return}target=value;targetSymbols=Array.from(value);targetIndex=0;misses=[];if(/[\u0900-\u097F]/.test(value)){byId('font').value='Kruti Dev 010'}else{byId('font').value='Georgia'}applyFont();byId('textDialog').close();resetSession();renderTarget();renderLane(false);editor.focus();showToast(/[\u0900-\u097F]/.test(value)?'Hindi exercise · Kruti Dev':'English exercise · Georgia')}
function renderTarget(){editor.textContent='';for(var i=0;i<targetSymbols.length;i++)editor.appendChild(element('span',i<targetIndex?'done':i===targetIndex?'current':'future',targetSymbols[i]));byId('progress').textContent=targetIndex+' / '+targetSymbols.length;byId('count').textContent=metricsText(targetSymbols.slice(0,targetIndex).join(''));setTimeout(function(){var current=editor.querySelector('.current');if(current)current.scrollIntoView({block:'nearest',inline:'nearest'})},0)}
function englishHintFor(character){var normal=profile()==='remington'?remingtonNormal:inscriptNormal,shifted=profile()==='remington'?remingtonShift:inscriptShift;for(var r=0;r<codes.length;r++){for(var k=0;k<codes[r].length;k++){if(normal[r][k]===character)return latinLabel(codes[r][k],false);if(shifted[r][k]===character)return 'Shift + '+latinLabel(codes[r][k],true)}}return ''}
function renderLane(wrong){var lane=byId('lane');lane.textContent='';if(!targetSymbols.length){lane.appendChild(element('span','','Paste text to begin'));return}var start=Math.max(0,targetIndex-3),end=Math.min(targetSymbols.length,targetIndex+5);for(var i=start;i<end;i++){var className='lane-key';if(i<targetIndex)className+=' past';else if(i===targetIndex)className+=' current';if(wrong&&i===targetIndex)className+=' wrong';var card=element('div',className,visible(targetSymbols[i]));if(i===targetIndex&&/[\u0900-\u097F]/.test(targetSymbols[i])){var wrap=element('div','lane-current-wrap');wrap.appendChild(card);wrap.appendChild(element('div','english-hint',englishHintFor(targetSymbols[i])));lane.appendChild(wrap)}else lane.appendChild(card)}byId('broken').textContent=misses.length?'Broken keys: '+misses.slice(-12).map(function(item){return '◼ '+item}).join('  '):'Broken keys: none';byId('progress').textContent=targetIndex+' / '+targetSymbols.length}
function processBuster(output,keyLabel,code){if(!targetSymbols.length||targetIndex>=targetSymbols.length)return;var expected=targetSymbols[targetIndex],correct=output===expected;recordAttempt(correct);if(correct){}else{misses.push((keyLabel||output)+'→'+visible(expected));showToast('Missed · expected '+visible(expected));flashCode(code,true)}targetIndex++;renderTarget();renderLane(!correct);if(targetIndex>=targetSymbols.length){clearInterval(timerHandle);timerHandle=null;timerArmed=false;leaveFocus();setTimeout(function(){finishSession()},120)}}
function keyOutput(event){if(event.key===' ')return ' ';if(event.key==='Enter')return '\n';if(event.key==='Tab')return '\t';return mappedOutput(event.code,event.shiftKey)}
function makeResizable(handle,panel,minWidth,minHeight){if(!handle||!panel)return;var active=false,startX=0,startY=0,startWidth=0,startHeight=0,pointerId=null;function point(event){return event.touches&&event.touches.length?event.touches[0]:event}function begin(event){if(event.button!==undefined&&event.button!==0)return;event.preventDefault();event.stopPropagation();var p=point(event);active=true;startX=p.clientX;startY=p.clientY;startWidth=panel.getBoundingClientRect().width;startHeight=panel.getBoundingClientRect().height;pointerId=event.pointerId;if(handle.setPointerCapture&&pointerId!==undefined){try{handle.setPointerCapture(pointerId)}catch(ignore){}}document.documentElement.classList.add('panel-resizing')}function move(event){if(!active)return;event.preventDefault();var p=point(event),app=document.querySelector('.app'),availableWidth=app?app.clientWidth:window.innerWidth-36,effectiveMinWidth=Math.min(minWidth,availableWidth),effectiveMinHeight=Math.min(minHeight,window.innerHeight-20),nextWidth=Math.max(effectiveMinWidth,Math.min(availableWidth,startWidth+p.clientX-startX)),nextHeight=Math.max(effectiveMinHeight,Math.min(Math.max(effectiveMinHeight,window.innerHeight-30),startHeight+p.clientY-startY));panel.style.width=nextWidth+'px';panel.style.height=nextHeight+'px'}function end(event){if(!active)return;active=false;if(handle.releasePointerCapture&&pointerId!==null){try{handle.releasePointerCapture(pointerId)}catch(ignore){}}pointerId=null;document.documentElement.classList.remove('panel-resizing')}if(window.PointerEvent){handle.addEventListener('pointerdown',begin);handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',end)}else{handle.addEventListener('mousedown',begin);document.addEventListener('mousemove',move);document.addEventListener('mouseup',end);handle.addEventListener('touchstart',begin,{passive:false});document.addEventListener('touchmove',move,{passive:false});document.addEventListener('touchend',end)}}
function armPageScrollbar(){var timer=null,root=document.documentElement;function show(){root.classList.remove('page-scroll-idle');root.classList.add('page-scroll-active');clearTimeout(timer);timer=setTimeout(function(){root.classList.remove('page-scroll-active');root.classList.add('page-scroll-idle')},5000)}window.addEventListener('scroll',show,{passive:true});document.addEventListener('mousemove',function(event){if(window.innerWidth-event.clientX<28)show()},{passive:true});document.addEventListener('touchstart',show,{passive:true});show()}
byId('layout').addEventListener('change',renderKeyboard);byId('font').addEventListener('change',applyFont);
var formatButtons=document.querySelectorAll('[data-format]');for(var f=0;f<formatButtons.length;f++){formatButtons[f].addEventListener('mousedown',function(event){event.preventDefault();restoreSelection();document.execCommand(this.dataset.format,false,null);this.classList.toggle('active');saveSelection();editor.focus()})}
editor.addEventListener('mouseup',saveSelection);editor.addEventListener('keyup',saveSelection);editor.addEventListener('focus',saveSelection);
byId('timer').addEventListener('change',function(){if(this.value==='custom')byId('timerDialog').showModal();else setTimer(Number(this.value))});byId('applyTimer').addEventListener('click',function(){var seconds=Number(byId('hours').value)*3600+Number(byId('minutes').value)*60+Number(byId('seconds').value);if(seconds<1||seconds>10800){window.alert('Choose a time between 1 second and 3 hours.');return}byId('timerDialog').close();setTimer(seconds)});byId('cancelTimer').addEventListener('click',function(){byId('timerDialog').close();byId('timer').value='0'});
byId('keyboardToggle').addEventListener('click',function(){if(buster)return;var hidden=keyboardPanel.style.display==='none';keyboardPanel.style.display=hidden?'':'none';this.textContent=hidden?'Hide keyboard':'Show keyboard'});byId('busterToggle').addEventListener('click',function(){setBuster(!buster)});byId('replaceText').addEventListener('click',function(){byId('textDialog').showModal()});byId('beginText').addEventListener('click',loadTarget);byId('cancelText').addEventListener('click',function(){byId('textDialog').close();if(!target&&buster)setBuster(false)});byId('closeResults').addEventListener('click',function(){byId('resultsDialog').close()});
editor.addEventListener('paste',function(event){event.preventDefault();if(buster)return;var clipboard=event.clipboardData||window.clipboardData,html=clipboard&&clipboard.getData?clipboard.getData('text/html'):'',text=clipboard&&clipboard.getData?(clipboard.getData('text/plain')||clipboard.getData('Text')):'';text=sanitizeText(text);if(!text){showToast('Images and embedded objects cannot be pasted');return}if(html){var fragment=sanitizeRichHtml(html);if(fragment.textContent&&fragment.textContent.trim()){insertFragmentAtCursor(fragment);showToast('Pasted text · bold, italic and underline preserved');return}}insertAtCursor(text);showToast('Pasted text')});
editor.addEventListener('drop',function(event){event.preventDefault();showToast('Drag-and-drop is disabled · paste plain text instead')});editor.addEventListener('dragover',function(event){event.preventDefault()});
editor.addEventListener('input',function(){var blocked=editor.querySelectorAll('img,video,audio,iframe,object,embed,svg,canvas,table');for(var i=0;i<blocked.length;i++)blocked[i].remove();updateCount();saveSelection();scheduleCaret()});
editor.addEventListener('keydown',function(event){if(event.key==='Escape'){leaveFocus();return}if(event.key==='CapsLock'){setTimeout(function(){capsOn=event.getModifierState&&event.getModifierState('CapsLock');renderKeyboard()},0);return}if(event.ctrlKey||event.altKey||event.metaKey)return;var printable=event.key.length===1||event.key==='Enter'||event.key==='Tab';if(event.key==='Backspace'){if(buster){event.preventDefault();return}recordAttempt(false);flashCode('Backspace',false);return}if(!printable)return;var output=keyOutput(event);if(!output)return;flashCode(event.code,false);if(buster){event.preventDefault();processBuster(output,latinLabel(event.code,event.shiftKey||capsOn),event.code)}else if(isHindiFont()){event.preventDefault();recordAttempt(true);insertAtCursor(output)}else{recordAttempt(true)}});
document.addEventListener('keydown',function(event){if(event.key==='Escape')leaveFocus()});
document.addEventListener('contextmenu',function(event){var editable=event.target===editor||editor.contains(event.target)||event.target.tagName==='TEXTAREA'||event.target.tagName==='INPUT';if(!editable)event.preventDefault()});
document.addEventListener('mousedown',function(event){var interactive=event.target.closest&&event.target.closest('button,select,input,textarea,dialog');if(!interactive&&!editor.contains(event.target))event.preventDefault()});
editor.addEventListener('blur',saveSelection);window.addEventListener('blur',saveSelection);window.addEventListener('focus',function(){setTimeout(function(){if(!document.querySelector('dialog[open]')){editor.focus();restoreSelection();scheduleCaret()}},40)});document.addEventListener('visibilitychange',function(){if(!document.hidden)setTimeout(function(){if(!document.querySelector('dialog[open]')){editor.focus();restoreSelection();scheduleCaret()}},40)});
armPageScrollbar();makeResizable(byId('editorResizeGrip'),editorPanel,690,245);makeResizable(byId('keyboardResizeGrip'),keyboardPanel,690,230);makeResizable(byId('busterResizeGrip'),busterPanel,690,225);renderKeyboard();applyFont();updateCount();setTimeout(function(){editor.focus();saveSelection();scheduleCaret()},0);
})();